
allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

subprojects {
    project.pluginManager.withPlugin('com.android.library') {
        if (project.android.namespace == null) {
            def manifest = file("${project.projectDir}/src/main/AndroidManifest.xml")
            if (manifest.exists()) {
                def packageName = new XmlParser().parse(manifest).attribute('package')
                if (packageName != null) {
                    project.android.namespace = packageName
                }
            }
        }
        project.android.buildFeatures {
            buildConfig = true
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.layout.buildDirectory
}
